config/routes.rb
Matthew::Application.routes.draw do
  resources :products

  resources :devex_users do
    resources :transactions
    resources :paypal_accounts
  end

  resources :paypal_accounts do 
    collection do 
      get 'orphans'
    end
    member do 
      get 'map'
    end
    resources :transactions
  end
  
  devise_for :admins

  resources :transactions do 
    member do 
      get 'upload_to_qb'
    end
    collection do 
      get 'prepare_batch_upload_to_qb'
    end
  end
  match '/ipn' => 'paypal#ipn'
  match '/mappings/do_map' => 'mappings#do_map'
  resources :mappings
  resources :reports do
    collection do 
      get 'export'
    end
  end
  resources :users do 
    collection do 
      post 'find_users'
    end
  end

  match '/bulk_upload_sales_receipts_to_quickbooks' => 'transactions#bulk_upload_sales_receipts_to_quickbooks'
  match '/bulk_upload_credit_memos_to_quickbooks' => 'transactions#bulk_upload_credit_memos_to_quickbooks'  

  root :to => "reports#index"

end

app/controllers/mapping_controller.rb
class MappingController < ApplicationController
  def index
    @devex_users = DevexUser.find(:all)
  end
  
  def do_map
    @paypal_account = PaypalAccount.find(params[:paypal_account_id])
    @consultant = Consultant.find(params[:consultant_id])
    @devex_user = DevexUser.find_by_username(@consultant.username)
    if @devex_user.nil?
      @devex_user = DevexUser.new(:account_id => @consultant.id,
        :username => @consultant.username,
        :account_type => "Consultant",
        :first_name => @consultant.first_name,
        :last_name => @consultant.last_name)
      if @devex_user.save
        if @paypal_account.update_attributes(:devex_user_id => @devex_user.id)
          flash[:notice] = "#{@paypal_account.email} has been succesfully mapped to #{@devex_user.username}"
          redirect_to '/mapping'
        end
      end
    else
      @paypal_account.devex_user_id = @devex_user.id
      if @paypal_account.save
        if @paypal_account.update_attributes(:devex_user_id => @devex_user.id)
          flash[:notice] = "#{@paypal_account.email} has been succesfully mapped to #{@devex_user.username}"
          redirect_to '/mapping'
        end
      end
    end
  end
  
end

app/controllers/mappings_controller.rb
class MappingsController < ApplicationController
  def index
    @devex_users = DevexUser.page(params[:page]).order('created_at DESC')
  end
  
  def do_map
    @paypal_account = PaypalAccount.find(params[:paypal_account_id])
    @consultant = Consultant.find(params[:consultant_id])
    if @devex_user.nil?
      @devex_user = DevexUser.new(:account_id => @consultant.id,
        :username => @consultant.user.username,
        :account_type => "Consultant",
        :first_name => @consultant.first_name,
        :last_name => @consultant.last_name)
      if @devex_user.save
        if @paypal_account.update_attributes(:devex_user_id => @devex_user.id)
          flash[:notice] = "Paypal User #{@paypal_account.email} has been succesfully mapped to Devex User #{@devex_user.username}"
          redirect_to '/mappings'
        end
      end
    else
      @paypal_account.devex_user_id = @devex_user.id
      if @paypal_account.save
        if @paypal_account.update_attributes(:devex_user_id => @devex_user.id)
          flash[:notice] = "#{@paypal_account.email} has been succesfully mapped to #{@devex_user.username}"
          redirect_to '/mappings'
        end
      end
    end
  end
  
end

app/helpers/mapping_helper.rb
module MappingHelper
end

app/views/mappings/_sidebar.html.haml
%ul
  %li= link_to "Reconcile Accounts", orphans_paypal_accounts_path
  / %li= link_to "Link Accounts", paypal_accounts_path
  %li=# link_to "Query Quickbooks", "#"

app/views/mappings/index.html.haml
#page-title
  %h3 Mapped Accounts List
  %h4 Displays reconciliation between Devex accounts and their QB and Paypal accounts
#content-options
  #content-buttons
    =link_to "Link Incoming Paypal Accounts", orphans_paypal_accounts_path, :class => "awesome orange"  
%br
%center
  = will_paginate @devex_users
%table.table2
  %thead
    %tr
      %th
      %th{:scope => "col"} Name
      %th{:scope => "col"} Devex Account Type
      %th{:scope => "col"} Paypal Accounts
      %th{:scope => "col"} QB Account     
      %th{:scope => "col"} Transactions
      
  %tbody
    - @devex_users.each do |devex_user|
      %tr
        %th{:scope => "row"}= devex_user.username 
        %td= [devex_user.first_name, devex_user.last_name].join(" ")
        %td= devex_user.account_type
        %td= link_to devex_user.paypal_accounts.count, devex_user_paypal_accounts_path(devex_user)
        - if devex_user.qb_member_name.blank?
          %td= link_to "Edit", edit_devex_user_path(devex_user)
        - else
          %td= link_to devex_user.qb_member_name, edit_devex_user_path(devex_user), :class => "cool-link-red"
        %td= link_to devex_user.transactions.count, devex_user_transactions_path(devex_user)
  %center
    = will_paginate @devex_users
    = page_entries_info @devex_users
  