config/routes.rb
Matthew::Application.routes.draw do
  resources :products

  resources :devex_users do
    resources :transactions
    resources :paypal_accounts
  end

  resources :paypal_accounts do 
    collection do 
      get 'orphans'
    end
    member do 
      get 'map'
    end
    resources :transactions
  end
  
  devise_for :admins

  resources :transactions do 
    member do 
      get 'upload_to_qb'
    end
    collection do 
      get 'prepare_batch_upload_to_qb'
    end
  end
  match '/ipn' => 'paypal#ipn'
  match '/mappings/do_map' => 'mappings#do_map'
  resources :mappings
  resources :reports do
    collection do 
      get 'export'
    end
  end
  resources :users do 
    collection do 
      post 'find_users'
    end
  end

  match '/bulk_upload_sales_receipts_to_quickbooks' => 'transactions#bulk_upload_sales_receipts_to_quickbooks'
  match '/bulk_upload_credit_memos_to_quickbooks' => 'transactions#bulk_upload_credit_memos_to_quickbooks'  

  root :to => "reports#index"

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.xml
  def index
    if params[:devex_user_id]
      @devex_user = DevexUser.find params[:devex_user_id]
      @transactions = @devex_user.transactions
    elsif params[:paypal_account_id]
      @paypal_account = PaypalAccount.find params[:paypal_account_id]
      @transactions = @paypal_account.transactions
    else
      @transactions = Transaction.all
    end
    @total_amount = @transactions.sum(:amount)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.xml
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.xml
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.xml
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully created.') }
        format.xml  { render :xml => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.xml
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.xml
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to(transactions_url) }
      format.xml  { head :ok }
    end
  end
  
  def prepare_batch_upload_to_qb
    @transactions = Transaction.for_next_bulk_update
    case params[:list_of]
    when 'invoice'
      @transactions = @transactions.invoices
      @form_path = bulk_upload_sales_receipts_to_quickbooks_path
    when 'credit'
      @transactions = @transactions.credits
      @form_path = bulk_upload_credit_memos_to_quickbooks_path
    end
  end
  
  def upload_to_qb
    @transaction = Transaction.find(params[:id])
    @transaction.upload_to_quickbooks
    if @transaction.uploaded_to_qb
      flash[:success]
    else
        if @transaction.paypal_account and @transaction.paypal_account.devex_user and !@transaction.paypal_account.devex_user.qb_member_name.blank?
          flash[:error] = "Incomplete Mapping"
        else
          flash[:error] = "Error encountered while trying to upload transaction to QB"
        end
    end
    redirect_to request.referer
  end
  
  def bulk_upload_sales_receipts_to_quickbooks
    count = Transaction.invoices.for_next_bulk_update.where(:id => params[:for_upload][:ids]).count
    Transaction.upload_batch_sales_receipt(params[:for_upload][:ids])
    flash[:notice] = "#{count} Transactions have been uploaded by bulk"
    redirect_to reports_path
  end
  
  def bulk_upload_credit_memos_to_quickbooks
    count = Transaction.credits.for_next_bulk_update.where(:id => params[:for_upload][:ids]).count
    Transaction.upload_batch_credit_memo(params[:for_upload][:ids])
    flash[:notice] = "#{count} Transactions have been uploaded by bulk"
    redirect_to reports_path
  end  
  
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :user_type %><br />
    <%= f.text_field :user_type %>
  </div>
  <div class="field">
    <%= f.label :transaction_reference %><br />
    <%= f.text_field :transaction_reference %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/_sidebar.html.haml
%ul

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.haml
#page-title
  %h3 Listing transactions

Total: Amount
= @total_amount
USD

%table.table2
  %thead
    %tr
      %th{:scope => "col"} Transaction Type
      %th{:scope => "col"} Transaction Reference    
      %th{:scope => "col"} Paypal User
      %th{:scope => "col"} Devex User
      %th{:scope => "col"} Amount

  - @transactions.each do |transaction|
    %tr
      %td= transaction.transaction_type 
      %td= link_to transaction.transaction_reference, transaction_path(transaction)
      %td
        = transaction.paypal_account.full_name
        (
        = transaction.paypal_account.email
        )
      %td
        - if transaction.paypal_account and transaction.paypal_account.devex_user 
          =link_to transaction.paypal_account.devex_user.full_name, devex_user_transactions_path(transaction.paypal_account.devex_user)
      %td
        - if transaction.amount
          = transaction.amount
          USD

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/prepare_batch_upload_to_qb.html.haml
= form_tag @form_path do 

  = submit_tag "Batch to Quickbooks"

  %table.table2
    %thead
      %tr
        %th Upload to QB
        %th{:scope => "col"} Transaction Reference    
        %th{:scope => "col"} Paypal User
        %th{:scope => "col"} Devex User
        %th{:scope => "col"} Amount
      
    - @transactions.each do |transaction|
      %tr
        %td= check_box_tag "for_upload[ids][]",  transaction.id, true
        
        %td= link_to transaction.transaction_reference, transaction_path(transaction)
        %td
          = transaction.paypal_account.full_name
          (
          = transaction.paypal_account.email
          )
        %td
          - if transaction.paypal_account and transaction.paypal_account.devex_user 
            =link_to transaction.paypal_account.devex_user.full_name, devex_user_transactions_path(transaction.paypal_account.devex_user)
        %td
          - if transaction.amount
            = transaction.amount
            USD
    
  = submit_tag "Batch to Quickbooks"

app/views/transactions/show.html.haml
#page-title
  %h3 Transaction Details

%b Transaction reference : 
= @transaction.transaction_reference 
%br

%b Transaction type :
= @transaction.transaction_type
%br

%b Transaction Date
= @transaction.created_at.to_s(:long)
%br

%b Status :
= @transaction.status
%br

%b Paypal Account ID :
= @transaction.payer_id
%br

%b Paypal Email :
= @transaction.payer_email
%br

%b Amount
= @transaction.amount
USD

%fieldset
  %legend Paypal Transaction Information
  %table
    - @transaction.attributes.each do |k, v|
      - unless k == 'ipn_data'
        %tr
        %td= k
        %td= v

= link_to 'Edit', edit_transaction_path(@transaction)
= link_to 'Back', transactions_path 