config/routes.rb
Matthew::Application.routes.draw do
  resources :products

  resources :devex_users do
    resources :transactions
    resources :paypal_accounts
  end

  resources :paypal_accounts do 
    collection do 
      get 'orphans'
    end
    member do 
      get 'map'
    end
    resources :transactions
  end
  
  devise_for :admins

  resources :transactions do 
    member do 
      get 'upload_to_qb'
    end
    collection do 
      get 'prepare_batch_upload_to_qb'
    end
  end
  match '/ipn' => 'paypal#ipn'
  match '/mappings/do_map' => 'mappings#do_map'
  resources :mappings
  resources :reports do
    collection do 
      get 'export'
    end
  end
  resources :users do 
    collection do 
      post 'find_users'
    end
  end

  match '/bulk_upload_sales_receipts_to_quickbooks' => 'transactions#bulk_upload_sales_receipts_to_quickbooks'
  match '/bulk_upload_credit_memos_to_quickbooks' => 'transactions#bulk_upload_credit_memos_to_quickbooks'  

  root :to => "reports#index"

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @date_from = params[:date_from] || 1.month.ago
    @date_to = params[:date_to] || 1.days.from_now
    if params[:date_from] and params[:date_to] 
      if params[:product] and params[:product] != "ALL"
         @product = Product.find params[:product]
       end
       @transactions_arel = Transaction.where(:created_at => db_date(@date_from)..db_date(@date_to))

       case params[:list_of]
       when 'invoice'
         @transactions_arel = @transactions_arel.invoices
       when 'credit'
         @transactions_arel = @transactions_arel.credits
       end

       unless @product.nil?
         @transactions_arel = @transactions_arel.where(:product => @product.paypal_product_code)
       end

       @transactions = @transactions_arel.page(params[:page]).includes([{:paypal_account => :devex_user}])
       @total = @transactions_arel.sum(:amount)
    else        
      @transactions = Transaction.page(params[:page])
      @total = Transaction.sum(:amount)
    end
  end
  
  def export
    @date_from = db_date(params[:date_from])
    @date_to = db_date(params[:date_to])
    
    if params[:product] and params[:product] != "ALL"
      @product = Product.find params[:product]
    end
    
    @transactions_arel = Transaction.where(:created_at => @date_from..@date_to)

    case params[:list_of]
    when 'invoice'
      @transactions_arel = @transactions_arel.invoices
    when 'credit'
      @transactions_arel = @transactions_arel.credits
    end

    unless @product.nil?
      @transactions_arel = @transactions_arel.where(:product => @product.paypal_product_code)
    end

    @transactions = @transactions_arel.includes([{:paypal_account => :devex_user}])
    @total = @transactions_arel.sum(:amount)
    
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet
    sheet1.name = "#{params[:list_of]} : #{params[:date_from]} to #{params[:date_to]}"

    sheet1.row(0).concat ['Paypal Transaction ID', 'Paypal Email', 'Devex Username', 'Product', 'Amount', 'Date']
    @transactions.each do |transaction|
      sheet1.row(@transactions.index(transaction) + 1).concat [transaction.transaction_reference, 
        transaction.payer_email,
        transaction.devex_user_full_name,
        transaction.product,
        transaction.amount.to_s,
        transaction.created_at ]
    end

    format = Spreadsheet::Format.new :color => :blue,
                                     :weight => :bold,
                                     :size => 18

    sheet1.row(0).default_format = format
    bold = Spreadsheet::Format.new :weight => :bold
    6.times do |x| sheet1.row(x + 1).set_format(0, bold) end
    filepath = "#{RAILS_ROOT}/tmp/"
    filename = "test.xls"
    book.write(filepath + filename)
    timeout = 500
    counter = 0
    until ((File.size(filepath + filename) > 0) or (counter > timeout))
      sleep(4)
      counter = counter + 5
    end
    send_file(filepath + filename)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_sidebar.html.haml
%ul
  %li= link_to "Reports Dashboard", reports_path
/ %ul
/   %li= link_to "IPM", "#"
/   %li= link_to "SBM", "#"
/   %li= link_to "EM", "#"
/   %li= link_to "Paypal", "#"
/   %li= link_to "Quickbooks", "#"

app/views/reports/index.html.haml
#page-title
  %h3 Dashboard
.notifications
  .notice
    = Transaction.count 
    Transactions
    %br
    = orphan_paypal_accounts_count
    needs to get linked
    / %br
    / = uploadable_transactions_count
    / have not yet been uploaded to quickbooks
    %br
    =# invoices_for_next_batch_update
    = prepare_invoices_for_next_batch_update
    Batch uploadable
    %br
    =# credit_memos_for_next_batch_update
    = prepare_credit_memos_for_next_batch_update    
    Batch uploadable
    
#content-options
  %fieldset
    %legend Filter
    = form_tag(reports_path, :method => 'get') do 
      I want a list of 
      = select_tag "list_of", options_for_select([["Sales Revenues", "invoice"], ["Credit Memos", "credit"]], params[:list_of])
      %br
      From
      = calendar_date_select_tag "date_from", @date_from, :popup => "force"
      To
      = calendar_date_select_tag "date_to", @date_to, :popup => "force"
      %br
      For the Product
      = select_tag "product", options_for_select(Product.all.map{|x| [x.name, x.id]} + ['ALL'], params[:product])
      %br    
      = submit_tag "Filter"

    
  
  Export to 
  = link_to "Excel", export_reports_path(:date_from => @date_from, :date_to => @date_to, :product => params[:product], :list_of => params[:list_of]), :class => "awesome blue small"
  =# link_to "PDF","#", :class => "awesome green small"
%div{:style => "clear:both"}

- if params[:list_of] == 'credit'
  Total Amount Credited : 
- else
  Total Sales Revenue : 

= @total
USD
  
%br
  %center
    = will_paginate @transactions
%table
  %thead
    %tr
      %th Paypal Transaction ID
      %th Paypal Email
      %th Devex User
      %th Product
      %th Amount
      %th Date
      %th In QB?

  - @transactions.each do |transaction|    
    %tbody
      %tr
        %td=link_to transaction.transaction_reference, transaction_path(transaction)
        %td
          / = link_to transaction.paypal_account.email, paypal_account_path(transaction.paypal_account), :class => "cool-link-blue"
          = transaction.paypal_account.email
        %td
          = link_to transaction.paypal_account.devex_user.full_name, devex_user_transactions_path(transaction.paypal_account.devex_user), :class => "cool-link-orange" if transaction.paypal_account.devex_user
        %td= transaction.product
        %td{:style => "font-weight:bold;color:#{transaction.classification.eql?('credit') ? 'red' : 'green'}"}= transaction.amount.to_s + " USD" unless transaction.amount.blank?
        %td= transaction.created_at
        %td= link_to transaction.uploaded_to_qb?.to_s, upload_to_qb_transaction_path(transaction)
%center
  = will_paginate @transactions
  = page_entries_info @transactions      