config/routes.rb
Matthew::Application.routes.draw do
  resources :products

  resources :devex_users do
    resources :transactions
    resources :paypal_accounts
  end

  resources :paypal_accounts do 
    collection do 
      get 'orphans'
    end
    member do 
      get 'map'
    end
    resources :transactions
  end
  
  devise_for :admins

  resources :transactions do 
    member do 
      get 'upload_to_qb'
    end
    collection do 
      get 'prepare_batch_upload_to_qb'
    end
  end
  match '/ipn' => 'paypal#ipn'
  match '/mappings/do_map' => 'mappings#do_map'
  resources :mappings
  resources :reports do
    collection do 
      get 'export'
    end
  end
  resources :users do 
    collection do 
      post 'find_users'
    end
  end

  match '/bulk_upload_sales_receipts_to_quickbooks' => 'transactions#bulk_upload_sales_receipts_to_quickbooks'
  match '/bulk_upload_credit_memos_to_quickbooks' => 'transactions#bulk_upload_credit_memos_to_quickbooks'  

  root :to => "reports#index"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Matthew
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults 
    = csrf_meta_tag
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'print.css', :media => 'print'
    = stylesheet_link_tag 'style.css', :media => 'style'
    = stylesheet_link_tag 'formtastic', 'formtastic_changes'
    /[if IE]
      = stylesheet_link_tag 'ie.css', :media => 'screen, projection'
    = calendar_date_select_includes
    = yield :head
  %body.two-columns
    #container
      #header
        #toplinks
          - if admin_signed_in?
            =link_to current_admin.email, "#"
            |
            =link_to "Logout", destroy_admin_session_path
          - else
            = link_to "Login", new_admin_session_path

        #pagetitle
          Matthew
      #topnav
        %ul
          %li= link_to "Reports", reports_path
          %li= link_to "Reconcile Accounts", mappings_path
          %li.last= link_to "Products", products_path

      #sidebar
        - if File.exists?("#{RAILS_ROOT}/app/views/#{params["controller"]}/_sidebar.html.haml")
          = render :partial => "sidebar"      
        - else
          %ul
      #content
        #content-inner
          #notifications-outer
            #notifications-inner
              - if notice
                .notice= notice
              - if alert
                .alert= alert
          %div{:style => "clear:both"}
          = yield      
          %div{:style => "clear:both"}
      #footer
        Footer Text Goes Here
  